javax.imageio.IIOException: Can't read input file!
	at javax.imageio.ImageIO.read(ImageIO.java:1301)
	at com.levins.webportal.certificate.client.UI.ClientPanel.<init>(ClientPanel.java:155)
	at com.levins.webportal.certificate.client.RunClientApp.main(RunClientApp.java:11)
javax.imageio.IIOException: Can't read input file!
	at javax.imageio.ImageIO.read(ImageIO.java:1301)
	at com.levins.webportal.certificate.client.UI.ClientPanel.<init>(ClientPanel.java:155)
	at com.levins.webportal.certificate.client.RunClientApp.main(RunClientApp.java:11)
javax.imageio.IIOException: Can't read input file!
	at javax.imageio.ImageIO.read(ImageIO.java:1301)
	at com.levins.webportal.certificate.client.UI.ClientPanel.<init>(ClientPanel.java:155)
	at com.levins.webportal.certificate.client.RunClientApp.main(RunClientApp.java:11)
javax.imageio.IIOException: Can't read input file!
	at javax.imageio.ImageIO.read(ImageIO.java:1301)
	at com.levins.webportal.certificate.client.UI.ClientPanel.<init>(ClientPanel.java:155)
	at com.levins.webportal.certificate.client.RunClientApp.main(RunClientApp.java:11)
javax.imageio.IIOException: Can't read input file!
	at javax.imageio.ImageIO.read(ImageIO.java:1301)
	at com.levins.webportal.certificate.client.UI.ClientPanel.<init>(ClientPanel.java:154)
	at com.levins.webportal.certificate.client.RunClientApp.main(RunClientApp.java:11)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: Q:\08_01_2016\W00011.pfx (The system cannot find the file specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:154)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: Q:\08_01_2016\W00011.pfx (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: Q:\08_01_2016\W00021.pfx (The system cannot find the file specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:154)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: Q:\08_01_2016\W00021.pfx (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:223)
	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:337)
	at java.io.DataInputStream.readUTF(DataInputStream.java:589)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:124)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.lang.Exception
	at com.levins.webportal.certificate.client.Client.run(Client.java:69)
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromList(Client.java:182)
	at com.levins.webportal.certificate.client.Client.run(Client.java:66)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null11_01_2016\W_IT.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromList(Client.java:182)
	at com.levins.webportal.certificate.client.Client.run(Client.java:66)
Caused by: java.io.FileNotFoundException: null11_01_2016\W_IT.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.lang.Exception
	at com.levins.webportal.certificate.client.Client.run(Client.java:69)
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.lang.Exception
	at com.levins.webportal.certificate.client.Client.run(Client.java:69)
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.io.FileNotFoundException
	at com.levins.webportal.certificate.client.MailSender.attachMultipleFile(MailSender.java:141)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:110)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: null07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:117)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:117)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:119)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:119)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:128)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:119)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:157)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:119)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:157)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:119)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:157)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:119)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:157)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:117)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:128)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
javax.mail.internet.AddressException: Missing '>' in string ``<07_01_2016\>'' at position 13
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:817)
	at javax.mail.internet.InternetAddress.parseHeader(InternetAddress.java:663)
	at javax.mail.internet.MimeMessage.getAddressHeader(MimeMessage.java:734)
	at javax.mail.internet.MimeMessage.getRecipients(MimeMessage.java:565)
	at javax.mail.Message.getAllRecipients(Message.java:318)
	at javax.mail.internet.MimeMessage.getAllRecipients(MimeMessage.java:580)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.internet.AddressException: Missing '>' in string ``<07_01_2016\>'' at position 13
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:817)
	at javax.mail.internet.InternetAddress.parseHeader(InternetAddress.java:663)
	at javax.mail.internet.MimeMessage.getAddressHeader(MimeMessage.java:734)
	at javax.mail.internet.MimeMessage.getRecipients(MimeMessage.java:565)
	at javax.mail.Message.getAllRecipients(Message.java:318)
	at javax.mail.internet.MimeMessage.getAllRecipients(MimeMessage.java:580)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.internet.AddressException: Missing '>' in string ``<07_01_2016\>'' at position 13
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:817)
	at javax.mail.internet.InternetAddress.parseHeader(InternetAddress.java:663)
	at javax.mail.internet.MimeMessage.getAddressHeader(MimeMessage.java:734)
	at javax.mail.internet.MimeMessage.getRecipients(MimeMessage.java:565)
	at javax.mail.Message.getAllRecipients(Message.java:318)
	at javax.mail.internet.MimeMessage.getAllRecipients(MimeMessage.java:580)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.internet.AddressException: Missing '>' in string ``<07_01_2016\>'' at position 13
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:817)
	at javax.mail.internet.InternetAddress.parseHeader(InternetAddress.java:663)
	at javax.mail.internet.MimeMessage.getAddressHeader(MimeMessage.java:734)
	at javax.mail.internet.MimeMessage.getRecipients(MimeMessage.java:565)
	at javax.mail.Message.getAllRecipients(Message.java:318)
	at javax.mail.internet.MimeMessage.getAllRecipients(MimeMessage.java:580)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.internet.AddressException: Missing '>' in string ``<07_01_2016\>'' at position 13
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:817)
	at javax.mail.internet.InternetAddress.parseHeader(InternetAddress.java:663)
	at javax.mail.internet.MimeMessage.getAddressHeader(MimeMessage.java:734)
	at javax.mail.internet.MimeMessage.getRecipients(MimeMessage.java:565)
	at javax.mail.Message.getAllRecipients(Message.java:318)
	at javax.mail.internet.MimeMessage.getAllRecipients(MimeMessage.java:580)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.internet.AddressException: Missing '>' in string ``<07_01_2016\>'' at position 13
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:817)
	at javax.mail.internet.InternetAddress.parseHeader(InternetAddress.java:663)
	at javax.mail.internet.MimeMessage.getAddressHeader(MimeMessage.java:734)
	at javax.mail.internet.MimeMessage.getRecipients(MimeMessage.java:565)
	at javax.mail.Message.getAllRecipients(Message.java:318)
	at javax.mail.internet.MimeMessage.getAllRecipients(MimeMessage.java:580)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.internet.AddressException: Missing '>' in string ``<07_01_2016\>'' at position 13
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:817)
	at javax.mail.internet.InternetAddress.parseHeader(InternetAddress.java:663)
	at javax.mail.internet.MimeMessage.getAddressHeader(MimeMessage.java:734)
	at javax.mail.internet.MimeMessage.getRecipients(MimeMessage.java:565)
	at javax.mail.Message.getAllRecipients(Message.java:318)
	at javax.mail.internet.MimeMessage.getAllRecipients(MimeMessage.java:580)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.internet.AddressException: Missing '>' in string ``<07_01_2016\>'' at position 13
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:817)
	at javax.mail.internet.InternetAddress.parseHeader(InternetAddress.java:663)
	at javax.mail.internet.MimeMessage.getAddressHeader(MimeMessage.java:734)
	at javax.mail.internet.MimeMessage.getRecipients(MimeMessage.java:565)
	at javax.mail.Message.getAllRecipients(Message.java:318)
	at javax.mail.internet.MimeMessage.getAllRecipients(MimeMessage.java:580)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
javax.mail.internet.AddressException: Missing '>' in string ``<07_01_2016\>'' at position 13
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:817)
	at javax.mail.internet.InternetAddress.parseHeader(InternetAddress.java:663)
	at javax.mail.internet.MimeMessage.getAddressHeader(MimeMessage.java:734)
	at javax.mail.internet.MimeMessage.getRecipients(MimeMessage.java:565)
	at javax.mail.Message.getAllRecipients(Message.java:318)
	at javax.mail.internet.MimeMessage.getAllRecipients(MimeMessage.java:580)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at com.levins.webportal.certificate.client.Client.run(Client.java:51)
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at com.levins.webportal.certificate.client.Client.run(Client.java:51)
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_02.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_03.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: C:\distr\cert07_01_2016\W00000001_04.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: Q:\11_01_2016\W999999.pfx (The system cannot find the file specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createSingleCert(Client.java:126)
	at com.levins.webportal.certificate.client.Client.run(Client.java:62)
Caused by: java.io.FileNotFoundException: Q:\11_01_2016\W999999.pfx (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at com.levins.webportal.certificate.client.Client.run(Client.java:51)
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1996)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1240)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Invalid address

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1849)
	... 6 more
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: C:\distr\cert11_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1290)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at com.levins.webportal.certificate.client.MailSender.sendMail(MailSender.java:116)
	at com.levins.webportal.certificate.client.Client.createUserFromFile(Client.java:155)
	at com.levins.webportal.certificate.client.Client.run(Client.java:64)
Caused by: java.io.FileNotFoundException: C:\distr\cert11_01_2016\W00000001_01.pfx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at javax.activation.FileDataSource.getInputStream(FileDataSource.java:97)
	at javax.activation.DataHandler.writeTo(DataHandler.java:305)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1645)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1241)
	... 5 more
java.sql.SQLException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:113)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:754)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:972)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1192)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3415)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3499)
	at com.levins.webportal.certificate.data.FromInsisData.insertInToDB(FromInsisData.java:127)
	at com.levins.webportal.certificate.data.FromInsisData.main(FromInsisData.java:65)
java.sql.SQLException: ORA-00926: missing VALUES keyword

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:113)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:754)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:972)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1192)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3415)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3499)
	at com.levins.webportal.certificate.data.FromInsisData.insertInToDB(FromInsisData.java:127)
	at com.levins.webportal.certificate.data.FromInsisData.main(FromInsisData.java:65)
java.sql.SQLException: ORA-00926: missing VALUES keyword

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:113)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:754)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:972)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1192)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3415)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3499)
	at com.levins.webportal.certificate.data.FromInsisData.insertInToDB(FromInsisData.java:127)
	at com.levins.webportal.certificate.data.FromInsisData.main(FromInsisData.java:65)
java.sql.SQLException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:113)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:754)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:972)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1192)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3415)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3499)
	at com.levins.webportal.certificate.data.FromInsisData.insertInToDB(FromInsisData.java:127)
	at com.levins.webportal.certificate.data.FromInsisData.main(FromInsisData.java:65)
java.sql.SQLException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:113)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:754)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:972)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1192)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3415)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3499)
	at com.levins.webportal.certificate.data.FromInsisData.insertInToDB(FromInsisData.java:127)
	at com.levins.webportal.certificate.data.FromInsisData.main(FromInsisData.java:65)
java.sql.SQLException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:113)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:754)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:972)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1192)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3415)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3499)
	at com.levins.webportal.certificate.data.FromInsisData.insertInToDB(FromInsisData.java:127)
	at com.levins.webportal.certificate.data.FromInsisData.main(FromInsisData.java:65)
java.sql.SQLException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:113)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:754)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:972)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1192)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3415)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3499)
	at com.levins.webportal.certificate.data.FromInsisData.insertInToDB(FromInsisData.java:127)
	at com.levins.webportal.certificate.data.FromInsisData.main(FromInsisData.java:65)
java.sql.SQLException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:113)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:754)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:972)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1192)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3415)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3499)
	at com.levins.webportal.certificate.data.FromInsisData.insertInToDB(FromInsisData.java:127)
	at com.levins.webportal.certificate.data.FromInsisData.main(FromInsisData.java:65)
java.sql.SQLException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:113)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:754)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:972)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1192)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3415)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3499)
	at com.levins.webportal.certificate.data.FromInsisData.insertInToDB(FromInsisData.java:127)
	at com.levins.webportal.certificate.data.FromInsisData.main(FromInsisData.java:65)
java.sql.SQLException: Io exception: Got minus one from a read call
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:113)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:147)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:257)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:389)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:454)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:802)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at com.levins.webportal.certificate.data.FromInsisData.createConnectionToServer(FromInsisData.java:152)
	at com.levins.webportal.certificate.data.FromInsisData.insertInToDB(FromInsisData.java:111)
	at com.levins.webportal.certificate.data.FromInsisData.main(FromInsisData.java:65)
java.sql.SQLException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:113)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:754)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:972)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1192)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3415)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3499)
	at com.levins.webportal.certificate.data.FromInsisData.insertInToDB(FromInsisData.java:127)
	at com.levins.webportal.certificate.data.FromInsisData.main(FromInsisData.java:65)
java.sql.SQLException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:113)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:754)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:972)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1192)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3415)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3499)
	at com.levins.webportal.certificate.data.FromInsisData.insertInToDB(FromInsisData.java:122)
	at com.levins.webportal.certificate.data.FromInsisData.main(FromInsisData.java:65)
